# Makefile for Writing Make Files Example
# *****************************************************
# Variables to control Makefile operation
 
CC = g++
CFLAGS = -Wall -g
 
# ****************************************************
# Targets needed to bring the executable up to date
 
cohen_p1: cohen_p1.o
    $(CC) $(CFLAGS) -o cohen_p1 cohen_p1.o 
 
# The main.o target can be written more simply
 
cohen_p1.o: cohen_p1.cpp
    $(CC) $(CFLAGS) -c cohen_p1.cpp
 
clean: 
